services:

  application:
    image: ghcr.io/henedioneto/devops-lab:latest

    container_name: devops-lab

    ports:
      - "8080:8080"

    environment:
      APP_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine

    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v3.5.0

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus-data:/prometheus

    depends_on:
      - application

  grafana:
    image: grafana/grafana:12.1.1

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana

    depends_on:
      - prometheus

volumes:
  redis-data:
  prometheus-data:
  grafana-data: