spring.application.name=devops-lab

server.port=8080

app.name=${APP_NAME:devops-lab}
app.version=${APP_VERSION:0.0.1-SNAPSHOT}
app.environment=${APP_ENV:local}

management.endpoints.web.exposure.include=health,info,metrics,mappings,prometheus
management.endpoint.health.show-details=always

management.info.env.enabled=true

info.app.name=${app.name}
info.app.version=${app.version}
info.app.environment=${app.environment}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}