spring.application.name=devops-lab

app.name=${APP_NAME:devops-lab}
app.version=${APP_VERSION:0.0.1-SNAPSHOT}
app.environment=${APP_ENV:local}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true